# Generated by Django 4.2.5 on 2023-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy_1', models.CharField(max_length=30)),
                ('remedy_2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=60)),
                ('composition', models.CharField(max_length=80)),
            ],
        ),
    ]
